export { CarritoPage   } from "../pages/carrito/carrito";
export { CategoriasPage } from "../pages/categorias/categorias";
export { OrdenesPage } from "../pages/ordenes/ordenes";
export { OrdenesDetallePage } from "../pages/ordenes-detalle/ordenes-detalle";
export { PorCategoriasPage } from "../pages/por-categorias/por-categorias";
export { ProductoPage } from "../pages/producto/producto";
export { TabsPage } from "../pages/tabs/tabs";
export {  HomePage } from "../pages/home/home";
export { LoginPage } from "../pages/login/login";
